Improved design in Card View
ilyakooo0/podphoenix pull request #10
Opened 2022-12-01 15:02 UTC by nicolascolla

![](https://i.imgur.com/xNr7wWf.jpg)

2022-12-04 13:56 UTC, ilyakooo0 requested changes
I am not opposed to the new design, but don't want it to be a performance regression. Podphoenix is already slower then I would like (:

2022-12-04 13:56 UTC, ilyakooo0 commented on app/ui/PodcastsTab.qml
>          });
This seems like a performance regression. Instead of sending one SQL query for all podcasts we now send an SQL query for every podcast.

2022-12-05 16:44 UTC, nicolascolla commented on app/ui/PodcastsTab.qml
>          });
@ilyakooo0, sorry about that! This seems to have been carried over from Podbird, hence the regression.

2022-12-06 13:39 UTC, ilyakooo0 approved these changes

2022-12-06 13:40 UTC, merged